version: "3"
services:
  llm_fuzz:
    depends_on:
      redis_service:
        condition: service_healthy
    build:
      context: .
      dockerfile: llm.Dockerfile
    tty: true
    environment:
      #- REDIS_HOST=redis_service // for MacOS or custom network
      - REDIS_HOST=localhost
      - REDIS_PASSWORD=password
      #- LLM_HOST=ollama // for MacOS or custom network
      - LLM_HOST=localhost
    network_mode: host
  redis_service:
    image: redis:latest
    ports:
      - 6379:6379
    command: >
      --requirepass password
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli --pass password ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    network_mode: host
  llm_service:
    image: ollama/ollama
    # ports:
    #   - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: host